urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib.comments.models import Comment
from django.contrib import admin
from django.views.generic.simple import redirect_to, direct_to_template
admin.autodiscover()


from oac.views import contributor_activity
from oac.views import statistics_ingest
from oac.admin_views import institution_change_location
from oac.admin_views import institution_view_groups
from oac.admin_site import contrib_staff_site

from contact.views import contactusmessage
from request_acct.views import request_archon_at


urlpatterns = patterns('',
    #(r'^admin/', direct_to_template, {'template':'admin_site_maintenance.html'}),#admin only site shutdown notice, uncomment to display static message.
    # /admin/OAC_admin/ points to the Django default admin site
    (r'^admin/request_hosted_acct/(?P<type>.*)', request_archon_at),
    (r'^admin/request_hosted_acct/', request_archon_at),
    (r'^admin/OAC_admin/institution-activity', contributor_activity),
    (r'^admin/OAC_admin/contributor-activity', contributor_activity),
    (r'^admin/OAC_admin/ingest-statistics', statistics_ingest),
    (r'^admin/OAC_admin/oac/institution/(\d+)/viewgroups/', institution_view_groups),
    (r'^admin/oac/institution/(\d+)/viewgroups/', institution_view_groups),
    (r'^admin/OAC_admin/oac/institution/(\d+)/changelocation/', institution_change_location),
    (r'^admin/OAC_admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/OAC_admin/', include(admin.site.urls)),
    # /admin/ points to custom AdminSite in oac/admin_site.py
    (r'^admin/oac/institution/(\d+)/changelocation/', institution_change_location),
    (r'^admin/', include(contrib_staff_site.urls)),

    (r'^admin/accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^admin/accounts/logout/$', 'django.contrib.auth.views.logout', {
        'next_page':'/'} ),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {
        'next_page':'/'} ),

    (r'^contact/', contactusmessage),

    (r'djsite/xtf/', include('xtf.urls')),
    (r'djsite/themed_collection/', include('themed_collection.urls')),

    (r'djsite/', include('oac.urls')),

    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media'}),
    (r'^css/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media/css'}),
    (r'^js/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media/js'}),
    (r'^yui/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media/yui'}),

                       #(r'/', redirect_to, {'url':'/admin/'}),
                       #(r'', redirect_to, {'url':'/admin/'}),
)

contact/models.py
from django.db import models

class ContactUsMessage(models.Model):
    ISSUE_TYPES = (
        ('SP', 'Search Page'),
        ('BP', 'Browse Page'),
        ('SR', 'Search Results'),
        ('EAD', 'EAD View'),
        ('MARC', 'MARC View'),
        ('METS', 'METS View'),
        ('CF', 'Comments Feature'),
        ('SP', 'Static Page'),
        ('AI', 'Admin Interface'),
        ('PDF', 'PDF View'),
        ('X', 'To assign'),
    )
    STATUS = (
        ('N', 'New'),
        ('P', 'In-process'),
        ('W', 'Waiting'),
        ('D', 'Duplicate'),
        ('C', "Completed"),
        ('T', "Move to Trac"),
        ('F', "Move to FootPrints"),
        ('DFR', "Defer"),
        ('B', "Bogus"),
        ('X', "To assign"),
    )
    CATEGORIES = (
        ('D', 'Defect'),
        ('E', 'Enhancement'),
        ('C', 'Data clean up'),
        ('U', 'Design Change'),
        ('X', 'To assign'),
    )
    PRIORITIES = (
        ('B', 'Blocker'),
        ('C', 'Critical'),
        ('G', 'Major'),
        ('P', 'Minor'),
        ('T', 'Trivial'),
        ('S', 'Gravy'),
        ('X', 'To assign'),
    )
    ASSIGNEE_GROUPS = (
        ('U', 'User Experience Design'),
        ('W', 'Web Production'),
        ('P', 'Programming/Developemnt'),
        ('D', 'Data Acqs/Metadata Coordination'),
        ('O', 'Operations'),
        ('X', 'To assign'),
    )
    RELEASES = (
        ('0', 'OAC-L 3.9.3'),
        ('394', '3.94'),
        ('395', '3.95'),
        ('396', '3.96'),
        ('40', '4.0'),
        ('41', '4.1'),
        ('4', '4.XX'),
        ('X', 'Unknown'),
    )
    SOURCES = (
        ('E', 'Existing Record'),
        ('AT', "Archivist's Toolkit"),
        ('X', 'To assign'),
    )

    url_refer = models.URLField(verify_exists=False, max_length=255, blank=True)
    user_agent = models.CharField(max_length=255)
    name = models.CharField(max_length=255, blank=True)
    email = models.EmailField(max_length=255, blank=True)
    subject = models.CharField(max_length=255, blank=True)
    message = models.TextField()
    open = models.BooleanField(default=True)
    type_of_issue = models.CharField(max_length=4, blank=True,
                                     choices=ISSUE_TYPES, default='X')
    status = models.CharField(max_length=4, blank=True,
                              choices=STATUS, default='N')
    duplicate = models.ForeignKey('self', null=True, blank=True,
                                  related_name='duplicates')
    category = models.CharField(max_length=4, blank=True,
                                choices=CATEGORIES, default='X')
    priority = models.CharField(max_length=4, blank=True,
                                choices=PRIORITIES, default='X')
    assigned_group = models.CharField(max_length=4, blank=True,
                                      choices=ASSIGNEE_GROUPS, default='X')
    source = models.CharField(max_length=4, blank=True,
                              choices=SOURCES, default='X')
    release = models.CharField(max_length=4, blank=True,
                              choices=RELEASES, default='X')
    dependencies = models.TextField(blank=True)
    next_steps = models.TextField(blank=True)
    note = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def message_display(self):
        msg = self.message[0:127]
        if len(self.message) > 128:
            msg += '... (%d more characters)' % (len(self.message) - 128)
        return msg

    def __unicode__(self):
        return self.subject

    class Meta:
        ordering = ['-created_at', '-url_refer']

contact/views.py
import sys
from django.conf import settings
from django.forms import ModelForm
from django.forms import ValidationError
from django.shortcuts import render_to_response
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.views.decorators.cache import never_cache
import recaptcha.client.captcha as Captcha
from contact.models import *


class ContactForm(ModelForm):
    class Meta:
        model = ContactUsMessage

def check_for_spam(request):
    is_spam = True
    error_dict = {}
    user_challenge = request.POST.get('recaptcha_challenge_field')
    user_resp = request.POST.get('recaptcha_response_field')
    ip = request.META.get('REMOTE_ADDR')
    captcha_resp = Captcha.submit(user_challenge, user_resp,
                                     settings.RECAPTCHA_PRIVATE_KEY, ip
                                    )
    if captcha_resp.is_valid:
        is_spam = False
    else:
        error_dict['recaptcha'] = 'Word verification incorrect. Try again.'

    return is_spam, error_dict

def send_email(msg):
        # build message
        mail_msg = 'Subject:%s\n\nMessage:%s\n\nName:%s\n\nEmail:%s\n\nURL_Refer:%s\n\nUSER_AGENT:%s\n' % ( msg.subject,
                                    msg.message, msg.name,
                                    msg.email, msg.url_refer,
                                    msg.user_agent)
        sub = msg.subject
        if not sub:
            sub = msg.message[0:25]
        subject = sub
        subject = "OAC feedback: " + subject
#        try:
        send_mail(subject, mail_msg, 'oaccontact@ucop.edu',
                  settings.CONTACT_US_EMAILS)
#        except socket.error:
#            import sys
#            (t, val, tb) = sys.exc_info()
#            if repr(val)=="error(61, 'Connection refused')":
#                pass #no email service
#            else:
#                raise

@never_cache
def contactusmessage(request):
    ''' Create & insert a ContactUsMessage if valid, if not ignore.
    Redirect to thank you page regardless of outcome?
    '''
    error_logger = request.environ['wsgi.errors']
    #error_logger.write("HI FROM DJANGO CONTACT APP")
    refer_page = request.META.get('HTTP_REFERER','')
    if request.method == 'POST':
        refer_page = request.POST.get('url_refer', refer_page)
        if request.POST.get('cancel'):
            cancel_redir = "/"
            if refer_page:
                cancel_redir = refer_page
            return HttpResponseRedirect(cancel_redir)
        f = ContactForm(request.POST)
        f.spam_errors = {}
        try:
            #print >> sys.stderr, f.data
            f.base_fields['url_refer'].clean(unicode(f.data.get('url_refer')))
        except ValidationError:
            # bind f to new form with replaced url_refer
            # just sub any spaces for +
            myData = f.data.copy()
            myData['url_refer'] = f.data.get('url_refer','').replace(' ', '+')
            f = ContactForm(myData)
            #print >> sys.stderr, f.data
        if f.is_valid(): #should mean that url_refer, user_agent and message OK?
            (is_spam, error_dict) = check_for_spam(request)
            if not is_spam:
                msg = f.save(commit=False)
                msg.open = True
                msg.status = 'N'
                msg.type_of_issue = 'X'
                msg.category = 'X'
                msg.priority = 'X'
                msg.assigned_group = 'X'
                msg.source = 'X'
                #msg.save()
                if settings.SEND_CONTACT_US_EMAIL:
                    send_email(msg)
                return render_to_response('contactthanks.html',
                                          { 'refer_page': refer_page}
                                         )
            else:
                f.spam_errors = error_dict
                #LOG to wsgi.error in request.environ
                msg_err = 'DJSITE: FAIL SPAM TEST for message: %s | url:%s | user-agent:%s\n' \
                         % (f.cleaned_data['message'],
                            f.cleaned_data['url_refer'],
                            f.cleaned_data['user_agent']
                           )
                error_logger.write(msg_err.encode('utf-8'))
        else:
            msg_err = 'DJSITE: CONTACT FORM INVALID: msg:%s | url:%s | user-agent:%s | ERR:%s\n' \
                         % (f.data.get('message','NOMSG'),
                            f.data.get('url_refer', 'NOREFER'),
                            f.data.get('user_agent', 'NOUSERAGENT'),
                            f.errors
                           )
            error_logger.write(msg_err.encode('utf-8'))
            #            error_logger.write('DJSITE: CONTACT FORM ERRORS: %s\n' % f.errors)
    else:
        f = ContactForm()
    return render_to_response('contactus.html', { 'form' : f, 'refer_page':
                                                 refer_page , 'META' :
                                                 request.META, } )

contact/templates/contactthanks.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
{% load ssi_relative %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Online Archive of California</title>
<link rel="stylesheet" type="text/css" href="/yui/build/reset-fonts-grids/reset-fonts-grids.css" />
<link rel="stylesheet" type="text/css" href="/css/oac.css" />
</head>

<body>
<a name="top"></a>
<p><a class="jump-to-content" href="#content">Jump to Content</a></p>

<!-- BEGIN PAGE CLASS -->
<div class="static">

<!-- BEGIN YUI CONTAINER -->
<div id="custom-doc">

<!-- BEGIN YUI HEADER -->
<div id="hd">

<!-- BEGIN TOP HEADER -->
{% ssi_rel '' includes/top-header.html %}
<!--#include virtual="/includes/top-header.html" -->
<!-- END TOP HEADER -->

<!-- BEGIN TOP NAVIGATION -->
{% ssi_rel '' includes/topnav.html %}
<!--#include virtual="/includes/topnav.html" -->
<!-- END TOP NAVIGATION -->

</div>
<!-- END YUI HEADER -->

<!-- BEGIN YUI BODY -->
<div id="bd">
<a name="content"></a>

<!-- BEGIN ROW 1 -->
<div class="row1">
<div class="row1-left">

<div class="header-box">

<div class="heading">Contact Us</div>

<p><strong>Thanks for your feedback</strong></p>
</div>

<div class="content-box">

{% if refer_page %}
<a href='{{ refer_page }}'>Return to previous page</a>
{% endif %}

</div>
</div>

<div class="row1-right">
<div class="row1-right-content">

<div class="heading">Contact Information</div>

<div><strong>Mailing Address</strong><br><br>
    Online Archive of California<br>
    California Digital Library<br>
    Office of the President, University of California<br>
    415 20th Street, 4th Floor<br>
    Oakland, CA 94612-2901<br>
</div>
<br>
<br>

<div><strong>Phone/Fax</strong><br><br>
    CDL Helpline: (510) 987-0555<br>
    CDL Administration: (510) 987-0425<br>
    Fax: (510) 893-5212<br>
</div>

</div>
</div>

</div>
<!-- END ROW 1 -->
	
</div>
<!-- END YUI BODY -->

<!-- BEGIN YUI FOOTER -->
<div id="ft">

<!-- BEGIN FOOTER -->
{% ssi_rel '' includes/footer.html %}
<!--#include virtual="/includes/footer.html" -->
<!-- END FOOTER -->

</div>
<!-- END YUI FOOTER -->

</div>
<!-- END YUI CONTAINER -->

</div>
<!-- END PAGE CLASS -->

</body>
</html>

contact/templates/contactus.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
{% load ssi_relative %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Online Archive of California</title>
<link rel="stylesheet" type="text/css" href="/yui/build/reset-fonts-grids/reset-fonts-grids.css" />
<link rel="stylesheet" type="text/css" href="/css/oac.css" />
</head>

<body>
<a name="top"></a>
<p><a class="jump-to-content" href="#content">Jump to Content</a></p>

<!-- BEGIN PAGE CLASS -->
<div class="static">

<!-- BEGIN YUI CONTAINER -->
<div id="custom-doc">

<!-- BEGIN YUI HEADER -->
<div id="hd">

<!-- BEGIN TOP HEADER -->
{% ssi_rel '' includes/top-header.html %}
<!--#include virtual="/includes/top-header.html" -->
<!-- END TOP HEADER -->

<!-- BEGIN TOP NAVIGATION -->
{% ssi_rel '' includes/topnav.html %}
<!--#include virtual="/includes/topnav.html" -->
<!-- END TOP NAVIGATION -->

</div>
<!-- END YUI HEADER -->

<!-- BEGIN YUI BODY -->
<div id="bd">
<a name="content"></a>

<!-- BEGIN ROW 1 -->
<div class="row1">
<div class="row1-left">

<div class="header-box">

<div class="heading">Contact Us</div>

<p><strong>Send us your feedback</strong></p>
<p>Please let us know if you have technical problems, questions, or general
comments about the Online Archive of California.
</p>
</div>

<div class="content-box">

<form action="" method="POST">
    <p><input id="id_url_refer" type="hidden" name="url_refer" maxlength="255"
    value ="{{ refer_page }}" />
    </p>
    <p><input id="id_user_agent" type="hidden" name="user_agent" maxlength="255"
    value ="{{ META.HTTP_USER_AGENT }}" />
    </p>
    <p><label for="id_subject"><strong>Subject</strong></label></p>
    <p><input id="id_subject" type="text" name="subject" maxlength="255" 
    value="{{ form.data.subject }}"/>
    </p>
    <p><label for="id_message"><strong>Message</strong></label></p>
    <p><div style="color: red">{{ form.message.errors }}</div></p>
    <p><textarea id="id_message" rows="10" cols="40"
        name="message" >{{ form.data.message }}</textarea>
    </p>

    <p><strong>Word verification</strong></p>
    <p>(Please verify the word below before submitting your feedback.)</p>

    <p><div style="color: red">{{ form.spam_errors.recaptcha }}</div></p>

<script>
    var RecaptchaOptions = {
        theme : 'clean'
    }
</script>
<script type="text/javascript"
    src="http://api.recaptcha.net/challenge?k=6LcXmwIAAAAAAIaSRnI0ItW4FjahxiBM9m1aqqUp">
</script>

<noscript>
    <iframe
        src="http://api.recaptcha.net/noscript?k=6LcXmwIAAAAAAIaSRnI0ItW4FjahxiBM9m1aqqUp"
        height="300" width="500" frameborder="0">
    </iframe><br/>
    <textarea name="recaptcha_challenge_field" rows="3" cols="40">
    </textarea>
    <input type="hidden" name="recaptcha_response_field"
    value="manual_challenge" />
</noscript>

<br/><br/>
<p>
Optional: (If you would like a response to your feedback, please enter the following.)
</p>

<p><label for="id_name"><strong>Name</strong></label></p>
<p><input id="id_name" type="text" name="name" maxlength="255" 
    value="{{ form.data.name }}" />
    </p>
    <p><label for="id_email"><strong>Email</strong></label></p>
    <p><div style="color: red">{{ form.email.errors }}</div></p>
    <p><input id="id_email" type="text" name="email" maxlength="255" 
    value="{{ form.data.email}}"/>
    </p>

<p><input id="id_submit" type="submit" name="submit" value='Submit' />
<input id="id_cancel" type="submit" name="cancel" value='Cancel' /></p>

</form>

</div>
</div>

<div class="row1-right">
<div class="row1-right-content">

<div class="heading">Contact Information</div>

<div><strong>Mailing Address</strong><br/><br/>
    Online Archive of California<br/>
    California Digital Library<br/>
    Office of the President, University of California<br/>
    415 20th Street, 4th Floor<br/>
    Oakland, CA 94612-2901<br/>
</div>
<br/>
<br/>

<div><strong>Phone/Fax</strong><br/><br/>
    CDL Helpline: (510) 987-0555<br/>
    CDL Administration: (510) 987-0425<br/>
    Fax: (510) 893-5212<br/>
</div>

</div>
</div>

</div>
<!-- END ROW 1 -->
	
</div>
<!-- END YUI BODY -->

<!-- BEGIN YUI FOOTER -->
<div id="ft">

<!-- BEGIN FOOTER -->
{% ssi_rel '' includes/footer.html %}
<!--#include virtual="/includes/footer.html" -->
<!-- END FOOTER -->

</div>
<!-- END YUI FOOTER -->

</div>
<!-- END YUI CONTAINER -->

</div>
<!-- END PAGE CLASS -->

</body>
</html>