oac/urls.py
from django.conf.urls.defaults import *

from oac.models import Institution
from oac.views import institution_address_info_div
from oac.views import list_archivegrid

urlpatterns = patterns('',
    # /djsite/ points to AJAX interfaces
    url(r'^institution/address_info/div/(?P<parent>.*)::(?P<inst_name>.*)', institution_address_info_div),
    url(r'^institution/address_info/div/(?P<inst_name>.*)', institution_address_info_div),
    url(r'^archivegrid_list', list_archivegrid),

)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib.comments.models import Comment
from django.contrib import admin
from django.views.generic.simple import redirect_to, direct_to_template
admin.autodiscover()


from oac.views import contributor_activity
from oac.views import statistics_ingest
from oac.admin_views import institution_change_location
from oac.admin_views import institution_view_groups
from oac.admin_site import contrib_staff_site

from contact.views import contactusmessage
from request_acct.views import request_archon_at


urlpatterns = patterns('',
    #(r'^admin/', direct_to_template, {'template':'admin_site_maintenance.html'}),#admin only site shutdown notice, uncomment to display static message.
    # /admin/OAC_admin/ points to the Django default admin site
    (r'^admin/request_hosted_acct/(?P<type>.*)', request_archon_at),
    (r'^admin/request_hosted_acct/', request_archon_at),
    (r'^admin/OAC_admin/institution-activity', contributor_activity),
    (r'^admin/OAC_admin/contributor-activity', contributor_activity),
    (r'^admin/OAC_admin/ingest-statistics', statistics_ingest),
    (r'^admin/OAC_admin/oac/institution/(\d+)/viewgroups/', institution_view_groups),
    (r'^admin/oac/institution/(\d+)/viewgroups/', institution_view_groups),
    (r'^admin/OAC_admin/oac/institution/(\d+)/changelocation/', institution_change_location),
    (r'^admin/OAC_admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/OAC_admin/', include(admin.site.urls)),
    # /admin/ points to custom AdminSite in oac/admin_site.py
    (r'^admin/oac/institution/(\d+)/changelocation/', institution_change_location),
    (r'^admin/', include(contrib_staff_site.urls)),

    (r'^admin/accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^admin/accounts/logout/$', 'django.contrib.auth.views.logout', {
        'next_page':'/'} ),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {
        'next_page':'/'} ),

    (r'^contact/', contactusmessage),

    (r'djsite/xtf/', include('xtf.urls')),
    (r'djsite/themed_collection/', include('themed_collection.urls')),

    (r'djsite/', include('oac.urls')),

    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media'}),
    (r'^css/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media/css'}),
    (r'^js/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media/js'}),
    (r'^yui/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.PROJECT_PATH+'/site_media/yui'}),

                       #(r'/', redirect_to, {'url':'/admin/'}),
                       #(r'', redirect_to, {'url':'/admin/'}),
)

oac/models.py
import re
from django.db import models
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.models import ContentType

def get_institutions_for_user(user):
    #get the profiles and then institutions user belongs to
    insts = []
    for group in user.groups.all():
        grp_prof = GroupProfile.objects.get(group=group.id)
        insts.extend(grp_prof.institutions.all())
    return insts

def valid_ark(ark):
    '''Validates arks. Right now just boolean function
    This does a very basic sanity check on arks, but doesn't completely validate
    arks as per the spec: http://www.cdlib.org/inside/diglib/ark/arkspec.html
    This should be usable throughout OAC.
    '''
    #    if not re.match(r'ark:/(\d{5}|\d{9})/[a-zA-Z0-9]+$', ark):
    if not re.match(r'ark:/(\d{5}|\d{9})/[a-zA-Z0-9=#\*+@_\$%-\./]+$', ark):
        return False
    return True

class County(models.Model):
    '''California County List
    '''
    name = models.CharField(max_length=255, unique=True)
    
    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        #        db_table = u'counties'

class City(models.Model):
    name = models.CharField(max_length=255, unique=True)
    county = models.ForeignKey(County)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True) 
    custom_zoom_level = models.IntegerField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        #db_table = u'cities'

class Institution(models.Model):
    '''Contributing Institutions
    '''
    ark = models.CharField(max_length=255, unique=True, blank=True)
    parent_institution = models.ForeignKey('self', null=True, blank=True, related_name='children')
    parent_ark = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=255)#, blank=True)
    mainagency = models.CharField(max_length=255, null=True, blank=True)
    cdlpath = models.CharField(max_length=255, blank=True)
    address1 = models.CharField(max_length=255, blank=True)
    address2 = models.CharField(max_length=255, null=True, blank=True)
    city = models.ForeignKey(City)
    county = models.ForeignKey(County)
    zip4 = models.CharField(max_length=255, blank=True)
    url = models.URLField(max_length=255, blank=True)
    phone = models.CharField(max_length=63, null=True, blank=True)
    fax = models.CharField(max_length=63, null=True, blank=True)
    email = models.CharField(max_length=63, null=True, blank=True)
    region = models.CharField(max_length=255, null=True, blank=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    custom_zoom_level = models.IntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    isa_campus = models.NullBooleanField(null=True, blank=True, default=False)
    primary_contact = models.ForeignKey(User,
                                        related_name="contact_for_institution",
                                        null=True,
                                        blank=True)
    worldcat_harvest = models.NullBooleanField(null=True, blank=True, default=False, verbose_name="WorldCat Export", help_text="Share my institution's digital object metadata with OCLC, for inclusion in WorldCat and OAIster")
    archivegrid_harvest = models.NullBooleanField(null=True, blank=True, default=False, verbose_name="ArchiveGrid Export", help_text="I'm interested in listing my OAC collection guides in ArchiveGrid and WorldCat Please have OCLC contact me.")
    show_subjects = models.NullBooleanField(null=True, blank=True, default=False, verbose_name="Show EAD Subject Terms", help_text="Show subject terms from your EADs on the institution home page.")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def _get_has_collections(self):
        return self.collection_set.count()
    has_collections = property(_get_has_collections)

    def _get_stat_path(self):
        '''Rerutn the path for stats. Is just cdlpath with / replaced by
        -
        '''
        return self.cdlpath.replace('/','-')
    stat_path = property(_get_stat_path)

    def _get_name_doublelist(self):
        """Return the 'doublelist' form of the institution's name
        """
        name = ''
        if self.parent_institution:
            name += self.parent_institution.name + '::'
        name += self.name
        return name
    name_doublelist = property(_get_name_doublelist)

    @staticmethod
    def valid_name(name):
        if re.search(r'[&].+', name) != None:
            return False, 'Ampersands (&) can not be used in institution names'
        return True, 'Name OK'

    def __unicode__(self):
        name = ''
        name += self.name
        if self.parent_institution:
            name += ', Parent: ' + self.parent_institution.name
        return name

    def save(self, force_insert=False, force_update=False):
        '''Need to save any changes in url to InstituionUrl table
        '''
        # strip whitespace from arks
        self.ark = self.ark.strip()
        if not valid_ark(self.ark):
            raise ValueError('Invalid ark')
        if self.parent_institution:
            self.parent_ark = self.parent_institution.ark
        else:
            self.parent_ark = None
        #lookup self in db and compare url fields
        if not Institution.valid_name(self.name)[0]:
            raise ValueError(Institution.valid_name(self.name)[1])
        try:
            self_db = Institution.objects.get(pk=self.pk)
            if self.url != self_db.url:
                #add record to InstitutionUrl
                i_url = InstitutionUrl(institution=self_db, url=self_db.url)
                i_url.save()
            #if name has changed, create an entry in InstitutionOldName
            if self.name != self_db.name:
                i_oldname = InstitutionOldName(institution=self_db,
                                               name=self_db.name,
                                              )
                i_oldname.save()
        except Institution.DoesNotExist:
            #New institution
            pass
        return super(Institution, self).save(force_insert, force_update)

    class Meta:
        ordering = ['name']
        #db_table = u'institutions'

class InstitutionUrl(models.Model):
    '''Mapping for historic institution urls'''
    institution = models.ForeignKey(Institution, null=False)
    url = models.URLField()
    flag = models.CharField(max_length=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.institution.name + ' | ' + self.url

class InstitutionOldName(models.Model):
    '''Old names for institutions. Mainly used for interim mapping in the djsite
    view address lookup.
    '''
    institution = models.ForeignKey(Institution)
    name = models.CharField(max_length=255)#, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class GroupProfile(models.Model):
    group = models.OneToOneField(Group) #hook into Django.auth
    #directory = models.CharField(max_length=255, null=True, blank=True)
    institutions = models.ManyToManyField(Institution, blank=True)
    #note = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return unicode(self.group)

    class Meta:
        ordering = ('group__name',)
        #db_table = u'edit_groups'

class UserProfile(models.Model):
    user = models.OneToOneField(User) #hook into Django Auth
    phone = models.CharField(max_length=63, null=True, blank=True)
    #institutions = models.ManyToManyField(Institution, null=True, blank=True)
    #OAC_listserv = models.BooleanField(default=True)
    voroEAD_account = models.BooleanField(default=False)
    archon_user = models.CharField(max_length=32, null=True, blank=True)
    AT_application_user = models.CharField(max_length=32, null=True, blank=True)
    AT_database_user = models.CharField(max_length=32, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    
    def __unicode__(self):
        return self.user.__unicode__()

    class Meta:
        ordering = ['user__username']
        #db_table = u'institution_employees'

class MARCPrimaryNameDisplay(models.Model):
    campus_name = models.CharField(max_length=255)
    primary_loc = models.CharField(max_length=255)
    primary_loc_display = models.CharField(max_length=255, null=True, blank=True)
    flag = models.CharField(max_length=255, null=True, blank=True,
                           help_text='Set to r to remove entry from OAC')
    melvyl_name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.primary_loc

    class Meta:
        ordering = ('campus_name', )

class Location(models.Model):
    #institutions = models.ManyToManyField(Institution, blank=True, null=True)
    mai_code_location = models.CharField(max_length=255, blank=True)
    location_type = models.CharField(max_length=255, null=True, blank=True)
    region = models.CharField(max_length=255, null=True, blank=True)
    suppress = models.CharField(max_length=255, null=True, blank=True,)
    campus = models.CharField(max_length=255, blank=True)
    cmp = models.CharField(max_length=255, null=True, blank=True)
    primary_name = models.CharField(max_length=255, null=True, blank=True)
    campus_name = models.CharField(max_length=255, blank=True)

oac/templates/institution_change_location.html
<!-- template for changing the intitution's location
-->
{% extends "admin/base_site.html" %}

{% block userlinks %}
{%endblock userlinks %}

{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../../">Home</a> &rsaquo;
     <a href="../../">Institutions</a> &rsaquo;
     <a href="../">{{ object }}</a> &rsaquo;
     Change Coordinates
</div>
{% endif %}{% endblock %}

{% block extrahead %}
<!-- PUT JAVASCRIPT PULLINS HERE -->
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAPZhPbFDgyqqKaAJtfPgdhRQxAnOebRR8qqjlEjE1Y4ZOeQ67yxSVDP1Eq9oU2BZjw2PaheQ5prTXaw"
	type="text/javascript"></script>
<script src="/map/map_change_institution.js" type="text/javascript"></script>
<script type="text/javascript">
    function windowLoad() {
        load({{ object.latitude }}, {{ object.longitude }}, "{{ object.name|addslashes}}");
        {% for inst in other_insts %}
        loadOtherMarker({{ inst.latitude }}, {{ inst.longitude }}, "{{ inst.name|addslashes }}");
        {% endfor %}
    }
    window.onload = windowLoad;
</script>
{% endblock extrahead %}

{% block title %}
Change Coordinates | {{ object.name }}
{% endblock title %}

{% block content_title %}
<h2>Change location for {{ object.name }}</h2>
{% endblock content_title %}

{% block content %}
<h4>{{ update }}</h4>
<h3>Original Coordinates</h3>
<h3>Lat: {{ object.latitude }}</h3>
<h3>Lng: {{ object.longitude }}</h3>
Click and drag marker on map to actual location.

<div id="map" style="width: 600px; height: 540px"></div>

<h3>Current Coordinates</h3>
<form method="GET" action='.'>
    <h3>Lat:<input READONLY type="text" id="id_latitude" name="latitude" value="{{ object.latitude }}"/></h3>
    <h3>Lng:<input READONLY type="text" id="id_longitude" name="longitude" value="{{ object.longitude }}"/></h3>
    <input type="submit" id="id_update" name="update" value="Update coordinates"/>
</form>
<h3>{{ latitude }} </h3>
{% endblock content %}

oac/templates/institution_view_groups.html
<!-- template for getting groups for institution
-->
{% extends "admin/base_site.html" %}

{% block userlinks %}
{%endblock userlinks %}

{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../../">Home</a> &rsaquo;
     <a href="../../">Institutions</a> &rsaquo;
     <a href="../">{{ inst }}</a> &rsaquo;
     View Groups
</div>
{% endif %}{% endblock %}

{% block title %}
Group List | {{ inst.name }}
{% endblock title %}

{% block content_title %}
<h2>Groups for institution: {{ inst.name }}</h2>
{% endblock content_title %}

{% block content %}
<ul>
{% for group in groups %}
<li>{{ group.name }}</li>
{% endfor %}
</ul>

{% endblock content %}

oac/templates/statistics_dashboard.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>OAC Ingest Statistics Dashboard</title>

    <!-- Framework CSS -->
    <link rel="stylesheet" href="/css/blueprint-css/blueprint/screen.css" type="text/css" media="screen, projection, print">

    <!--[if lt IE 8]><link rel="stylesheet" href="/css/blueprint/ie.css" type="text/css" media="screen, projection, print">
<![endif]-->

    <!-- Import fancy-type plugin for the sample page. -->
    <link rel="stylesheet" href="/css/blueprint-css/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection, print">
     <style type="text/css">
.area {background:none repeat scroll 0 0 #E6EBEC; padding:0.8em; margin-bottom:1em;}
.ci {border:2px solid #DDDDDD; margin-bottom:1em; padding:0.8em; background:none repeat scroll 0 0 #E6EBEC;}
.img { text-decoration:none; } 
img {  border-style: none; }
h2 { color:#C2492C; }
h1 { margin-top:0.5em; }
     </style>

     {% comment %}
     !!!!============= THE FOLLOWING DOES NOT WORK, NOT SURE WHY YET ======!!!
     {% for field in dateForm %}
        {{ field.media }}
     {% endfor %}
     ADDED LINE BELOW WITH SUPPORT IN VIEW
     # this NOT WORK{{ media }} 
     {% endcomment %}
     <link rel="stylesheet" type="text/css" href="/media/css/base.css" />
     <link rel="stylesheet" type="text/css" href="/media/css/forms.css" />
     <!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/media/css/ie.css" /><![endif]-->

    <script type="text/javascript">
        window.__admin_media_prefix__ = '/media/';
    </script>

    <script type="text/javascript" src="/admin/OAC_admin/jsi18n/"></script>
     <script type="text/javascript" src="/media/js/core.js"></script>
     <script type="text/javascript" src="/media/js/jquery.min.js"></script>
     <script type="text/javascript" src="/media/js/jquery.init.js"></script>
     <!--
     <script type="text/javascript" src="/media/js/actions.min.js"></script>
     <script type="text/javascript" src="/media/js/SelectBox.js"></script>
     <script type="text/javascript" src="/media/js/SelectFilter2.js"></script>
     -->
     <script type="text/javascript" src="/media/js/calendar.js"></script>
     <script type="text/javascript" src="/media/js/admin/DateTimeShortcuts.js"></script>
     <script type="text/javascript" src="/media/js/inlines.min.js"></script>

  </head>
  <body>

    <div class="container">
      <h1>OAC Ingest Statistics Dashboard</h1>

      <div class="area span-24">
          <h2>Ingest object reports</h2>
          <form action="{% url oac.views.statistics_ingest %} " method="post">
                <fieldset>
                    <legend>METS objects for a given time period</legend>
                    {% for field in dateForm.visible_fields %}
                      <p class='datetime'>
                      {{ field.errors }}
                      {{ field.label_tag }}: {{ field }}
                      </p>
                    {% endfor %}
                    <input type="hidden" name='type' id="id_type" value="METS"/>
                  <input type="submit" value="Generate METS report" />
                  <input type="reset" value="Reset" />
                </fieldset>
            </form>
          <form action="{% url oac.views.statistics_ingest %} " method="post">
                <fieldset>
                    <legend>EAD documents for a given time period</legend>
                    {% for field in dateForm.visible_fields %}
                      <p class='datetime'>
                      {{ field.errors }}
                      {{ field.label_tag }}: {{ field }}
                      </p>
                    {% endfor %}
                    <input type="hidden" name='type' id="id_type" value="EAD"/>
                  <input type="submit" value="Generate EAD report" />
                  <input type="reset" value="Reset" />
                </fieldset>
            </form>
      </div>

      <a href='/admin/OAC_admin/contributor-activity/'>Get recent contributor activity report</a>

    </div>
  </body>
</html>